all:
  children:
   rke2_cluster:
     children:
       rke2_servers:
         hosts:
           k8sserver01t:
           k8sserver02t:
           k8sserver03t:
       rke2_agents:
         hosts:
           k8sworker01t:
           k8sworker02t:
           k8sworker03t:
           k8sworker04t:
           k8sworker05t:
           k8sworker06t:
           k8sworker07t:
