---

- name: Install open-iscsi packages
  package:
    name: open-iscsi
    state: present
  become: yes

- name: Enable iscsi daemon
  service:
    name: iscsid
    state: started
    enabled: yes
  become: yes
